/**
 * Home-page authentication, profile, and admin copy
 */

export const AUTH_COPY = {
  panelTitle: "Welcome to Helpchain",
  panelSubtitle: "Sign in or create an account — optional for this prototype.",
  signInTab: "Sign in",
  signUpTab: "Sign up",
  skip: "Skip — continue to roles",
  skipHint: "Sign in is not required to explore the prototype.",
  reopenAuth: "Sign in or sign up (optional)",
  continueWith: "Continue with",
  providers: {
    google: "Google",
    apple: "Apple",
    email: "Email",
    phone: "Phone",
  },
  email: {
    signInTitle: "Sign in with email",
    signUpTitle: "Create your account",
    nameLabel: "Full name",
    namePlaceholder: "Your name",
    emailLabel: "Email address",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Enter your password",
    confirmLabel: "Confirm password",
    submitSignIn: "Sign in",
    submitSignUp: "Continue",
    switchToSignUp: "New here? Create an account",
    switchToSignIn: "Already have an account? Sign in",
  },
  phone: {
    title: "Sign in with phone",
    signUpTitle: "Create account with phone",
    nameLabel: "Full name",
    namePlaceholder: "Your name",
    numberLabel: "Mobile number",
    numberPlaceholder: "(555) 123-4567",
    sendCode: "Send verification code",
    codeLabel: "Verification code",
    codePlaceholder: "6-digit code",
    codeSent: (phone: string) => `Enter the code sent to ${phone}.`,
    verify: "Verify and continue",
    changeNumber: "Use a different number",
  },
  roleSelection: {
    title: "How will you use Helpchain?",
    subtitle: "Choose your role. You can update this later in your profile.",
    requester: {
      title: "Requester",
      description: "I need situational assistance from nearby volunteers.",
    },
    volunteer: {
      title: "Volunteer",
      description: "I want to help people nearby when they need support.",
    },
    both: {
      title: "Both",
      description: "I may request help and also volunteer for others.",
    },
    continue: "Continue to profile setup",
  },
  requesterProfile: {
    title: "Requester profile",
    subtitle: "This information helps volunteers respond appropriately during a session.",
    disabilityLabel: "Disability type",
    disabilityPlaceholder: "Select disability type",
    emergencyNameLabel: "Emergency contact name",
    emergencyNamePlaceholder: "Contact full name",
    emergencyPhoneLabel: "Emergency contact phone",
    emergencyPhonePlaceholder: "(555) 987-6543",
    verificationTitle: "Requester verification",
    verificationSubtitle:
      "Before you can submit help requests, we need documentation confirming your accessibility needs.",
    documentNameLabel: "Document name",
    documentNamePlaceholder: "e.g. Medical assessment letter",
    documentDescLabel: "Document description",
    documentDescPlaceholder: "Briefly describe what the document confirms…",
    uploadLabel: "Supporting document",
    uploadHint: "PDF, JPG, or PNG up to 10 MB",
    uploadAction: "Choose file",
    uploadSelected: (name: string) => `Selected: ${name}`,
    submitVerification: "Submit for review",
    resubmitVerification: "Resubmit verification",
    status: {
      not_submitted: "Verification required before requesting help",
      pending_review: "Verification under review",
      verified: "Requester verified",
      rejected: "Verification declined",
      additional_docs_required: "Additional documents required",
    },
    adminNote: (note: string) => `Reviewer note: ${note}`,
  },
  volunteerProfile: {
    title: "Volunteer profile",
    subtitle: "Help requesters know who you are before they accept your help.",
    nameLabel: "Display name",
    namePlaceholder: "How you appear to requesters",
    avatarLabel: "Profile picture",
    descriptionLabel: "Short description",
    descriptionPlaceholder: "A few words about yourself and how you help…",
    languagesLabel: "Languages you speak",
    phoneLabel: "Mobile number for OTP verification",
    phonePlaceholder: "(555) 123-4567",
    otpTitle: "Verify your phone",
    otpSubtitle: "We send a one-time code to confirm your number before you can receive requests.",
    sendOtp: "Send verification code",
    verifyOtp: "Verify phone",
    otpSent: (phone: string) => `Enter the code sent to ${phone}.`,
    verified: "Phone verified",
    saveProfile: "Save volunteer profile",
  },
  profile: {
    title: "Your profile",
    tabs: {
      requester: "Requester",
      volunteer: "Volunteer",
      account: "Account",
    },
    edit: "Edit profile",
    save: "Save changes",
    cancel: "Cancel",
    signedInAs: (name: string) => `Signed in as ${name}`,
    roles: {
      requester: "Requester",
      volunteer: "Volunteer",
      both: "Requester & Volunteer",
    },
  },
  account: {
    title: "Account settings",
    deactivateTitle: "Deactivate account",
    deactivateDescription:
      "Your account will be disabled. You can contact support to reactivate within 30 days.",
    deactivateAction: "Deactivate account",
    deactivateConfirm: "Deactivate my account",
    deleteTitle: "Delete my data",
    deleteDescription:
      "Permanently remove your profile, verification records, and audit history in accordance with GDPR.",
    deleteAction: "Delete all my data",
    deleteConfirm: "Permanently delete",
    deleteWarning: "This action cannot be undone. All personal data will be removed.",
    gdprNote: "Your data is stored locally in this browser. Deletion removes all stored account information.",
  },
  signedIn: {
    welcome: (name: string) => `Welcome back, ${name}`,
    subtitle: "Choose how you want to use Helpchain today.",
    signOut: "Sign out",
    openProfile: "Profile",
    verifiedBadge: "Requester verified",
    volunteerVerifiedBadge: "Volunteer verified",
  },
  gate: {
    requesterUnverified: "Complete requester verification in your profile before requesting help.",
    volunteerUnverified: "Verify your phone in your profile before receiving help requests.",
  },
  admin: {
    title: "Verification console",
    subtitle: "Review requester documentation, approve access, and track verification history.",
    pendingTitle: "Pending reviews",
    noPending: "No requester verifications awaiting review.",
    auditTitle: "Verification audit log",
    noAudit: "No verification events recorded yet.",
    columns: {
      id: "ID",
      user: "User",
      time: "Time",
      result: "Result",
      note: "Note",
    },
    actions: {
      accept: "Accept",
      reject: "Reject",
      requestDocs: "Request additional documents",
    },
    reviewNoteLabel: "Reviewer note (optional)",
    reviewNotePlaceholder: "Add a note for the requester or audit trail…",
    documentSection: "Submitted documentation",
    viewProfile: "View requester details",
    results: {
      submitted: "Submitted",
      accepted: "Accepted",
      rejected: "Rejected",
      additional_docs_required: "Additional docs required",
    },
  },
  errors: {
    required: "Please fill in all required fields.",
    passwordMatch: "Passwords do not match.",
    invalidEmail: "Enter a valid email address.",
    invalidPhone: "Enter a valid phone number.",
    invalidCode: "Enter the 6-digit verification code.",
    accountNotFound: "No account found. Please sign up first.",
    accountExists: "An account with this identifier already exists. Sign in instead.",
    selectRole: "Select at least one role.",
    selectLanguage: "Select at least one language.",
    uploadRequired: "Please attach a supporting document.",
  },
  loading: {
    google: "Connecting to Google…",
    apple: "Connecting to Apple…",
    email: "Signing you in…",
    phone: "Verifying code…",
    submit: "Submitting…",
    save: "Saving…",
  },
} as const;
